//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinRunner.Resources.Help {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinRunner.Resources.Help.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        public static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Application.
        /// </summary>
        public static string DeleteApplication {
            get {
                return ResourceManager.GetString("DeleteApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Application.
        /// </summary>
        public static string EditApplication {
            get {
                return ResourceManager.GetString("EditApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program modifies the Windows Registry on the computer that it is started on. The Registry is a database for low-level settings and can be/is used by all parts of the operating system. Third-party applications, like WinRunner, can also use the Registry to store any settings they need to function better.
        ///
        ///WinRunner modifies only a single Registry key: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths
        ///
        ///Do NOT use WinRunner unless you know what you are doing and how modifying the ab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpCaution {
            get {
                return ResourceManager.GetString("HelpCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete a registered application, click the Delete button next to the application in the main window. A new window will pop up where you will confirm the deletion.
        ///
        ///Click the Delete button in the confirmation window to actually delete the application. This will immediately remove the Registry entry and you will no longer be able to start the application using Run.
        ///
        ///Deleting a Batch application will also delete the Batch file associated with it..
        /// </summary>
        public static string HelpDeleteApplication {
            get {
                return ResourceManager.GetString("HelpDeleteApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To edit a registered application, click the Edit button next to the application in the main window. A new window will pop up where the details can be modified.
        ///
        ///The steps at this point are the same as with registering a new application..
        /// </summary>
        public static string HelpEditApplication {
            get {
                return ResourceManager.GetString("HelpEditApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register an application, click the New Application button. A new window will pop up where the details will be filled in.
        ///
        ///Name is the text you will enter in order to start the application using the Run command. This does not have to be related to the actual name of the application. The name cannot contain the dot and backslash characters. The name must be unique among all the registered applications.
        ///
        ///Path is the full file path of the application on your computer. The icon of the application will be  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpNewApplication {
            get {
                return ResourceManager.GetString("HelpNewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinRunner lets you register an application with Windows. This means that application can be started using the Run command by entering the name with which it was registered. This can save some time as it doesn&apos;t require any mouse clicks.
        ///
        ///Any applications you create in this program will result in a matching key entry being created in the Windows Registry and you&apos;ll be able to start that application using Run immediately.
        ///
        ///Upon starting WinRunner it will search the Registry for any registered applications [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpOverview {
            get {
                return ResourceManager.GetString("HelpOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Application.
        /// </summary>
        public static string NewApplication {
            get {
                return ResourceManager.GetString("NewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/BenjinYap/WinRunner.
        /// </summary>
        public static string Repo {
            get {
                return ResourceManager.GetString("Repo", resourceCulture);
            }
        }
    }
}
